server:
  host: 0.0.0.0
  port: 3000
swagger:
  title: YoutubeRoom
  description: Documention of the API YoutubeRoom
  version: 1.0
  tag1: users
  tag2: videos
  tag3: rooms
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/youtubeRoom
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: true

